apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: prod
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stderr"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

