apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - nginx-configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - queue-deployment.yaml
  - scheduler-cronjob.yaml

